name: Update data

on:
  #schedule:
  #  - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Checkout concerts repository
        uses: actions/checkout@v2
        with:
          repository: pubrrr/concerts
          ref: react
          path: concerts
      - name: Debug
        run: |
          ls -la
          ls -la concerts
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '21'
      - name: Run concerts
        run: |
          cd concerts
          ./mvnw spring-boot:run
          cp concerts.json ..
        env:
          TELEGRAM_AUTH: ""
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          LASTFM_API_KEY: ${{ secrets.LASTFM_API_KEY }}
      - name: Debug
        run: |
          ls -la
          ls -la concerts
      - name: Commit concderts.json
        run: |
          git config --global user.email "fake@mail.com"
          git config --global user.name "GitHub Actions"
          git add concerts.json
          git commit -m "Update concerts.json"
          git push
